id: AE44C9292
title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
  Jamyang Khyentse Wangpo
type: translation
pechas:
- IE27653EE
- I69EAAC14
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:15.070800
  last_modified_at: 2023-01-04 12:35:15.070813
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IE27653EE/5AEC: '9533'
  I69EAAC14/D264: '9533'
